# Site settings
title: Xiaowei's dog
description: 即使说了那么多丧气的话 也一直在努力生活啊.
author:
  name: "坏脾气先生L"
  email: "myfoolish@126.com"
  url: "https://myfoolish.github.io/blog1/"
url:  "https://myfoolish.github.io/" # Actual base url of the website
baseurl: "blog1/"  # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 8
paginate_path: "/page:num/"

#SEO
twitter:
  username: meetgirls
  card: summary
facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/meetgirls
    - https://www.github.com/myfoolish
#    - https://www.linkedin.com/in/alessio-franceschi/
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
#lang: en_US
lang: zh-Hans

#Highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never